In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


## Take two numbers from the user and show their sum

In [5]:
x = float(input("Enter the first number : "))
y = float(input("Enter the second number : "))
sum = x + y
print("The sum of {0} and {1} is {2}".format(x, y, sum))

Enter the first number :  4
Enter the second number :  5


The sum of 4.0 and 5.0 is 9.0


## Take the base and height of a triangle and compute the area

In [10]:
b = input("Enter base of the triangle: ")
h = input("Enter heigh of the triangle: ")
area = ( float(b) + float(h) ) / 2
print("The area of {0} and {1} is {2}".format(b, h, area))

Enter base of the triangle:  8
Enter heigh of the triangle:  4


The area of 8 and 4 is 6.0


## Take from the user an array of integers, print True if the array length is 3 or more, and the first element and the last element are equal

In [19]:
arr = list(input("Enter your numbers: "))
size = len(arr)
if size >= 3 and arr[0] == arr[size - 1]:
    print("True")
else: 
    print("False")

Enter your numbers:  1 2 3 4 5 1


True


## Given 2 strings, return their concatenation, except omit the first char of each. The strings will be at least length 1

In [26]:
str1 = input("Enter your first string: ")
str2 = input("Enter your second string: ")
result = str1[1:] + str2[1:]
print("The concatenated string is: ", result)

Enter your first string:  Milk
Enter your second string:  Shake


The concatenated string is:  ilkhake


## All even numbers between 1 and 100

In [36]:
list = [x for x in range(2, 101, 2)]
print(list)

# or 
list = [x for x in range(1, 101, 1) if x%2 == 0]

#or 
list = []
for x in range(2, 101, 2):
    list.append(x)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


##  A list with 10 random numbers 

In [2]:
from random import randint
list = [randint(1, 10) for x in range(10)]
list

[2, 7, 1, 6, 1, 7, 2, 5, 8, 2]

## A list whose size is a random number of elements (between 0 and 10)

In [5]:
size = randint(1, 10)
list = [x for x in range(1, size)]
print(size)
list

3


[1, 2]

## Invent a loop that will search a list until it finds a certain number then print "found", otherwise it prints " Not found“

In [54]:
num  = int(input("Enter your target: "))
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
found = False
for x in list:
    if x == num:
        found = True
        break
if found:
    print("Target found")
else:
    print("Target not found")

Enter your target:  56


Target not found


## print only the even numbers in a list of integers

In [57]:
list = [1 , 5, 4, 9, 6, 3, 2]
for x in list:
    if x % 2 == 0:
        print(x)
# or 
for x in list:
    if x % 2 != 0:
        continue
    print(x)    

4
6
2
4
6
2


## Write Fibonacci function

In [74]:
def fib(n):
    a, b = 0, 1
    for i in range(n):
        print(a)
        a, b = b, a+b

In [75]:
fib(10)

0
1
1
2
3
5
8
13
21
34


In [1]:
 import numpy as np
 arr = np.array([1, 2, 3, 4, 5, 6, 7])
 print(arr[-3:-1])

[5 6]


In [3]:
 import numpy as np
 arr = np.array([1, 2, 3, 4, 5, 6, 7])
 print(arr[:4])

[1 2 3 4]


In [7]:
 import numpy as np
 arr = np.array([1, 2, 3, 4, 5, 6, 7])
 print(arr[::2])

[1 3 5 7]


In [9]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [11]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
 import numpy as np
 arr = np.array([1, 2, 3, 4, 5, 4, 4])
 x = np.where(arr == 4)
 print(x)

(array([3, 5, 6]),)


In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [17]:
import numpy as np
arr = np.array([41, 42, 43, 44])
 # Create an empty list
filter_arr = []
 # go through each element in arr
for element in arr:
 # if the element is higher than 42, set the value to True, otherwise False:
 if element > 42:
    filter_arr.append(True)
 else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
