## Numpy 

In [1]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [2]:
type(my_list)

list

In [46]:
import numpy as np
x = np.array(my_list)
print(x.ndim)
print(x.size)
print(x.dtype)

1
3
int64


In [9]:
type(x)

numpy.ndarray

In [18]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
y = np.array(my_matrix)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
type(y)

numpy.ndarray

In [20]:
y.shape

(3, 3)

In [21]:
np.arange(0, 10, 5)

array([0, 5])

In [22]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.zeros((5, 5, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [32]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.random.rand(5)

array([0.14406594, 0.10059791, 0.13920094, 0.78012141, 0.00818183])

In [35]:
np.random.rand(5, 2)

array([[0.87808356, 0.89380108],
       [0.43404645, 0.043985  ],
       [0.58791606, 0.60761475],
       [0.57997438, 0.98066835],
       [0.63460001, 0.32911266]])

In [36]:
np.random.randn(5)

array([-0.09315599, -0.65762361,  0.45567798, -1.51176053, -0.63966296])

In [38]:
np.random.randint(1, 100)

99

In [39]:
np.random.randint(1, 100, 10)

array([19, 79, 33, 63, 78,  2, 62, 60, 15, 66], dtype=int32)

In [40]:
np.random.randint(1, 100, (3, 2))

array([[82, 93],
       [95, 82],
       [28,  1]], dtype=int32)

In [52]:
arr = np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
arr.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [76]:
arr2 = np.array([33, 5, 6, 8, 50, 7, 12])
arr2

array([33,  5,  6,  8, 50,  7, 12])

In [63]:
arr2.max()

np.int64(50)

In [64]:
arr2.min()

np.int64(5)

In [66]:
arr2.argmax()

np.int64(4)

In [70]:
arr2[5]

np.int64(7)

In [71]:
arr2[1:5]

array([ 5,  6,  8, 50])

In [72]:
 arr2[:]

array([33,  5,  6,  8, 50,  7, 12])

In [73]:
slice_of_array = arr2[0:4]
slice_of_array

array([33,  5,  6,  8])

In [74]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99])

In [75]:
arr2

array([99, 99, 99, 99, 50,  7, 12])

In [78]:
arr2_copy = arr2.copy()
arr2_copy

array([33,  5,  6,  8, 50,  7, 12])

In [80]:
arr2_copy_slice = arr2_copy[0:4]
arr2_copy_slice[:] = 100
arr2_copy_slice


array([100, 100, 100, 100])

In [81]:
arr2

array([33,  5,  6,  8, 50,  7, 12])

In [82]:
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [84]:
arr_2d[0]

array([ 5, 10, 15])

In [85]:
arr_2d[0][0]

np.int64(5)

In [86]:
arr_2d[:2, 0:]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [87]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [88]:
arr_2d>4

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [89]:
arr_2d[arr_2d > 4]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [91]:
arr_2d+arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [92]:
arr_2d - arr_2d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [93]:
arr_r = np.arange(0,10)
arr_r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.sqrt(arr_r)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [95]:
np.log(arr_r)

C:\Users\rabab\AppData\Local\Temp\ipykernel_16160\3698953418.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr_r)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [96]:
np.exp(arr_r)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [97]:
np.sin(arr_r)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [98]:
np.cos(arr_r)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])